# Generated by Django 5.2.7 on 2025-10-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('hh_resume_link', models.CharField(max_length=200)),
                ('resume_content', models.TextField()),
                ('resume_ontology', models.JSONField()),
            ],
        ),
    ]
