# Generated by Django 5.2.7 on 2026-02-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_client_resume_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='source_type',
            field=models.CharField(choices=[('url', 'Ссылка HH.ru'), ('pdf', 'PDF'), ('md', 'Markdown')], default='url', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='hh_resume_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
