# Generated by Django 5.2.7 on 2025-10-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=20)),
                ('hh_resume_link', models.URLField()),
                ('resume_ontology', models.JSONField()),
            ],
        ),
    ]
